//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ajaxprj1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int contactId { get; set; }
        public string fName { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> bdate { get; set; }
        public string address { get; set; }
        public Nullable<byte> photo { get; set; }
        public bool ischecked { get; set; }
    }
}
